/* soappocService.cpp
   Generated by gSOAP 2.8.7 from test.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soappocService.h"

pocService::pocService()
{	pocService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

pocService::pocService(const struct soap &_soap) : soap(_soap)
{ }

pocService::pocService(soap_mode iomode)
{	pocService_init(iomode, iomode);
}

pocService::pocService(soap_mode imode, soap_mode omode)
{	pocService_init(imode, omode);
}

pocService::~pocService()
{ }

void pocService::pocService_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "urn:poc", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
};

void pocService::destroy()
{	soap_destroy(this);
	soap_end(this);
}

#ifndef WITH_PURE_VIRTUAL
pocService *pocService::copy()
{	pocService *dup = SOAP_NEW_COPY(pocService(*(struct soap*)this));
	return dup;
}
#endif

int pocService::soap_close_socket()
{	return soap_closesock(this);
}

int pocService::soap_force_close_socket()
{	return soap_force_closesock(this);
}

int pocService::soap_senderfault(const char *string, const char *detailXML)
{	return ::soap_sender_fault(this, string, detailXML);
}

int pocService::soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_sender_fault_subcode(this, subcodeQName, string, detailXML);
}

int pocService::soap_receiverfault(const char *string, const char *detailXML)
{	return ::soap_receiver_fault(this, string, detailXML);
}

int pocService::soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_receiver_fault_subcode(this, subcodeQName, string, detailXML);
}

void pocService::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void pocService::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *pocService::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

void pocService::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *pocService::soap_header()
{	return this->header;
}

int pocService::run(int port)
{	if (soap_valid_socket(bind(NULL, port, 100)))
	{	for (;;)
		{	if (!soap_valid_socket(accept()) || serve())
				return this->error;
			soap_destroy(this);
			soap_end(this);
		}
	}
	else
		return this->error;
	return SOAP_OK;
}

SOAP_SOCKET pocService::bind(const char *host, int port, int backlog)
{	return soap_bind(this, host, port, backlog);
}

SOAP_SOCKET pocService::accept()
{	return soap_accept(this);
}

int pocService::serve()
{
#ifndef WITH_FASTCGI
	unsigned int k = this->max_keep_alive;
#endif
	do
	{

#ifndef WITH_FASTCGI
		if (this->max_keep_alive > 0 && !--k)
			this->keep_alive = 0;
#endif

		if (soap_begin_serve(this))
		{	if (this->error >= SOAP_STOP)
				continue;
			return this->error;
		}
		if (dispatch() || (this->fserveloop && this->fserveloop(this)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this);
#else
			return soap_send_fault(this);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(this);
		soap_end(this);
	} while (1);
#else
	} while (this->keep_alive);
#endif
	return SOAP_OK;
}

static int serve_ns2__getS(pocService*);

int pocService::dispatch()
{	soap_peek_element(this);
	if (!soap_match_tag(this, this->tag, "ns2:getS"))
		return serve_ns2__getS(this);
	return this->error = SOAP_NO_METHOD;
}

static int serve_ns2__getS(pocService *soap)
{	struct ns2__getS soap_tmp_ns2__getS;
	struct ns2__getSResponse soap_tmp_ns2__getSResponse;
	soap_default_ns2__getSResponse(soap, &soap_tmp_ns2__getSResponse);
	soap_default_ns2__getS(soap, &soap_tmp_ns2__getS);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	if (!soap_get_ns2__getS(soap, &soap_tmp_ns2__getS, "ns2:getS", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->getS(soap_tmp_ns2__getS.species1, soap_tmp_ns2__getS.species2, soap_tmp_ns2__getS.s, soap_tmp_ns2__getS.x0, soap_tmp_ns2__getS.Tmin, soap_tmp_ns2__getS.Tmax, soap_tmp_ns2__getS.Npoints, soap_tmp_ns2__getS.logaritmic, soap_tmp_ns2__getSResponse.dat);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns2__getSResponse(soap, &soap_tmp_ns2__getSResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns2__getSResponse(soap, &soap_tmp_ns2__getSResponse, "ns2:getSResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns2__getSResponse(soap, &soap_tmp_ns2__getSResponse, "ns2:getSResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}
/* End of server object code */
